version: '3'
services:
  api:
    container_name: droperclone-api
    extends:
      file: ../common/docker-compose.yaml
      service: api

  database:
    container_name: database-1
    extends:
      file: ../common/docker-compose.yaml
      service: database
